# Generated by Django 4.2.6 on 2023-11-18 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore_app', '0002_msg_alter_product_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msg',
            name='mobile',
        ),
    ]
